### ISSUE TITLE
Best installation method ?

### ISSUE THREAD

**Issue by ashish10alex** [andres-lowrie/vim-sqlx#1]
Hi what is the recommended installation method ?
I ended up copying the contents of syntax folder onto `~/.config/nvim/syntax` folder followed by adding the line 
`autocmd BufNewFile,BufRead *.sqlx setfiletype sqlx` to by innit.vim file

Is there a better / recommended way?

**Comment by andres-lowrie** [comment]
I use pathogen https://github.com/tpope/vim-pathogen

and then I clone the repo down as per the instructions on that project.

I haven't tried with neovim, when I get home I'll check with my neovim setup and respond here; with neovim I use packer https://github.com/wbthomason/packer.nvim to manage plugins

**Comment by andres-lowrie** [comment]
this also loaded up in neovim without issues. btw

In terms of "better/recommended" I would say that you try a plugin manager instead of manually copying stuff; the flow to install, update, etc it much nicer

I mentioned pathogen and packer, but there's also https://github.com/search?q=vim-plug&ref=opensearch&type=repositories but really any one of those is going to be a better a way/experience with plugins

**Comment by magal1337** [comment]
hey @andres-lowrie  could you share with me how you installed this with your plugins.lua file using packer? BTW: I still noob to packer...

**Comment by ashish10alex** [comment]
I used [vimPlug](https://github.com/junegunn/vim-plug). So, I had to add just one line and run `:PlugInstall` 
```
Plug 'andres-lowrie/vim-sqlx'
```
For Packer it should be something along the lines of adding this and running -> `:PackerSync` followed by `:PackerInstall`
```
 use 'andres-lowrie/vim-sqlx'
 ```

**Comment by magal1337** [comment]
it worked with vimPlug! Thanks a lot @ashish10alex !

**Comment by andres-lowrie** [comment]
@magal1337 awesome you got it working! FYI for future travelers this also works with neovim, I have an example using lazy over here https://github.com/andres-lowrie/kickstart.nvim/blob/master/init.lua#L342 which is a fork of this wonderful repo https://github.com/nvim-lua/kickstart.nvim which I highly recommend to people that are interested in getting started with neovim
