### ISSUE TITLE
Attach this syntax plugin to custom dataform.nvim plugin

### ISSUE THREAD

**Issue by magal1337** [andres-lowrie/vim-sqlx#3]
Hey @andres-lowrie  how are you? After some time playing with your plugin which is really great, I also created a [dataform neovim plugin](https://github.com/magal1337/dataform.nvim) to boost my local workflow.

Right now it has the following functionalities:
- Compile dataform project when open sqlx file first time within neovim session or when write a sqlx file
- Compile dataform current model to sql script with bq cli validation (full load and incremental)
- Go to reference sqlx file when line has the ${ref()} pattern
- Run current dataform model (full or incremental)
- Run current dataform model assertions
- Run entire dataform project
- Run dataform specific tag

But still is missing the syntax highlight feature (because I still using yours =D) and I really want to integrate your functionality with mine. Would you like to contribute with your syntax highlight feature and create this unique plugin? Or can I add your plugin as reference to my Readme file (so if user needs syntax highlight it needs to install your plugin)?

btw: I will create the complete README file with all details in the next couple weeks

**Comment by andres-lowrie** [comment]
yeah I'll contribute for sure @magal1337 . Let me give it a look this weekend

**Comment by magal1337** [comment]
@andres-lowrie thanks buddy! I'll add the README file until Wednesday as well.

**Comment by andres-lowrie** [comment]
https://github.com/magal1337/dataform.nvim/pull/5
